-
  name: Install and configure httpd
  hosts: servers
  connection: local
  become: yes  # This assumes you need elevated privileges to install packages and manage services
  gather_facts: False
  tags: provisioning
  tasks:
    - name: Install apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure httpd service is enabled
      service:
        name: apache2
        state: started
        enabled: yes
