- name: Create AWS Target Group and Register EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  tasks:
    - name: Create a target group with instance targets
      community.aws.elb_target_group:
        name: ABL-group
        protocol: http
        port: 81
        vpc_id: vpc-02fcfa3a51c9ffe89
        region: us-east-1
        health_check_protocol: http
        health_check_path: /
        successful_response_codes: "200,250-260"
        targets:
          - Id: i-0b2c11a85dd1267e8
            Port: 80
          - Id: i-048d5cc22b036427a
            Port: 80
          - Id: i-0d2b4e9b87da46c06
            Port: 80
        state: present
        wait_timeout: 200
        wait: true
    - name: Create application load balancer
      community.aws.elb_application_lb:
        name: AplicationLoadBalancer
        security_groups:
          - launch-wizard-1
        region: us-east-1  
        subnets:
          - subnet-0b5ecf46f252f0e67
          - subnet-03286513962c68c4d
          - subnet-08d49dc941b4c0215
        listeners:
          - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
            Port: 80 # Required. The port on which the load balancer is listening.
            # The security policy that defines which ciphers and protocols are supported. The default is the current predefined security policy.
            #SslPolicy: ELBSecurityPolicy-2015-05
            #Certificates: # The ARN of the certificate
             # - CertificateArn: arn:aws:iam::123456789012:server-certificate/test.domain.com
            DefaultActions:
              - Type: forward # Required.
                TargetGroupName: ABL-group # Required. The name of the target group
        state: present
