- name: Create EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
    keypair: project
    instance_type: t2.micro
    image:  ami-0866a3c8686eaeeba
    wait: yes
    group: webserver
    instance_name: server
    region: us-east-1
    security_group: launch-wizard-2
    ec2_instance_count: 3

  tasks:
  - name: configuring security group for the instance
    ec2_group:
        name: "{{ security_group }}"
        description: launch-wizard-2 created 2024-11-19T10:37:44.370Z
        region: "{{ region }}"
        rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
        rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
  - name: creating ec2 instance
    ec2_instance:
        security_group: "{{ security_group }}"
        name: "{{ instance_name }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type}}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        count: "{{ ec2_instance_count }}"
        wait_timeout: 3
